import { PropertyValues } from "lit";
import { KucBase } from "../base/kuc-base";
import { BaseLabel } from "../base/label";
import { BaseError } from "../base/error";
export { BaseError, BaseLabel };
declare type Item = {
    label?: string;
    value?: string;
};
declare type DropdownProps = {
    className?: string;
    error?: string;
    id?: string;
    label?: string;
    value?: string;
    selectedIndex?: number;
    disabled?: boolean;
    requiredIcon?: boolean;
    visible?: boolean;
    items?: Item[];
};
export declare class Dropdown extends KucBase {
    className: string;
    error: string;
    id: string;
    label: string;
    value: string;
    selectedIndex: number;
    disabled: boolean;
    requiredIcon: boolean;
    visible: boolean;
    items: Item[];
    private _selectorVisible;
    private _groupEl;
    private _menuEl;
    private _itemsEl;
    private _buttonEl;
    private _labelEl;
    private _firstItemEl;
    private _lastItemEl;
    private _selectedItemEl;
    private _highlightItemEl;
    private _errorEl;
    private _timeoutID;
    private _GUID;
    constructor(props?: DropdownProps);
    private _setInitialValue;
    private _getSelectedLabel;
    private _getToggleIconSvgTemplate;
    shouldUpdate(changedProperties: PropertyValues): boolean;
    willUpdate(changedProperties: PropertyValues): void;
    update(changedProperties: PropertyValues): void;
    private _getSelectedIndex;
    private _getValue;
    render(): import("lit").TemplateResult<1>;
    firstUpdated(): void;
    updated(): Promise<void>;
    private _handleMouseDownDropdownItem;
    private _handleMouseOverDropdownItem;
    private _handleMouseLeaveMenu;
    private _handleMouseDownMenu;
    private _handleMouseDownDropdownToggle;
    private _handleMouseUpDropdownToggle;
    private _handleClickDropdownToggle;
    private _handleClickDocument;
    private _handleKeyDownDropdownToggle;
    private _actionShowMenu;
    private _actionHideMenu;
    private _actionToggleMenu;
    private _actionHighlightFirstMenuItem;
    private _actionHighlightLastMenuItem;
    private _actionHighlightPrevMenuItem;
    private _actionHighlightNextMenuItem;
    private _actionClearAllHighlightMenuItem;
    private _setHighlightAndActiveDescendantMenu;
    private _actionHighlightMenuItem;
    private _actionUpdateValue;
    private _actionSetActiveDescendant;
    private _actionRemoveActiveDescendant;
    private _updateContainerWidth;
    private _getScrollbarWidthHeight;
    private _getDistanceToggleButton;
    private _setMenuPositionAboveOrBelow;
    private _setMenuPositionLeftOrRight;
    private _setMenuPosition;
    private _scrollToView;
    private _actionResizeScrollWindow;
    private _getStyleTagTemplate;
    private _isCheckedItem;
    private _getItemTemplate;
    private _getDropdownIconSvgTemplate;
}
