import { PropertyValues } from "lit";
import { KucBase } from "../base/kuc-base";
declare type Item = {
    label?: string;
    value?: string;
};
declare type MultiChoiceProps = {
    className?: string;
    error?: string;
    id?: string;
    label?: string;
    value?: string[];
    selectedIndex?: number[];
    disabled?: boolean;
    requiredIcon?: boolean;
    visible?: boolean;
    items?: Item[];
};
export declare class MultiChoice extends KucBase {
    className: string;
    error: string;
    id: string;
    label: string;
    disabled: boolean;
    requiredIcon: boolean;
    visible: boolean;
    items: Item[];
    selectedIndex: number[];
    value: string[];
    private _menuEl;
    private _itemsEl;
    private _GUID;
    private _valueMapping;
    constructor(props?: MultiChoiceProps);
    private _setInitialValue;
    shouldUpdate(changedProperties: PropertyValues): boolean;
    willUpdate(changedProperties: PropertyValues): void;
    update(changedProperties: PropertyValues): void;
    render(): import("lit").TemplateResult<1>;
    private _getValueMapping;
    private _getValidValue;
    private _getValidSelectedIndex;
    private _setValueAndSelectedIndex;
    private _handleMouseDownMultiChoiceItem;
    private _handleMouseOverMultiChoiceItem;
    private _handleMouseLeaveMultiChoiceItem;
    private _handleKeyDownMultiChoice;
    private _getMultiChoiceCheckedIconSvgTemplate;
    private _isCheckedItem;
    private _getMenuItemTemplate;
    private _getStyleTagTemplate;
    private _setActiveDescendant;
    private _handleChangeValue;
    private _getNewValueMapping;
}
export {};
