name: test

on:
  pull_request:
    branches: [master]
jobs:
  Run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: |
          npm ci
          npm i @actions/core --no-save
      - name: generate licenses
        id: generate_licenses
        uses: ./.github/actions/generate_licenses
      - run : echo ${{ steps.generate_licenses.outputs.license_file_path }}
