name: Amplify Auto Deploy Document Live

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DOCUMENT_REGION }}
      - name: Create Amplify deployment
        id: create_deployment
        run: |
          output=$(aws amplify create-deployment --app-id ${{ secrets.AWS_DOCUMENT_APP_ID }} --branch-name staging)
          echo "all=$output" >> $GITHUB_OUTPUT
      - name: Upload Document Zip file
        run: |
          echo ${{ steps.create_deployment.outputs.all }}