name: Amplify Document Production Environment

on:
  push

jobs:
  publishOnMasterRelease:
    name: Deploying on Amplify Document Production Environment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ZIP_FILE_NAME: build_prod
      BRANCH_NAME: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies on document
        run: pnpm install --frozen-lockfile
        working-directory: docs/document
      - name: Build document
        run: pnpm run build
        working-directory: docs/document
      - name: Create deployment zip file
        run: zip -r $ZIP_FILE_NAME *
        working-directory: docs/document/build