name: Amplify Auto Deploy Document Production Environment

on:
  push:

jobs:
  publishOnMasterRelease:
    name: Deploying on Netlify Document Production Environment
    runs-on: ubuntu-latest
    env:
      ZIP_FILE_NAME: build_prod
      BRANCH_NAME: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document
      - name: Build document
        run: npm run build
        working-directory: docs/document
      - name: Create Zip Deployment Package
        run: zip -r $ZIP_FILE_NAME *
        working-directory: docs/document/build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DOCUMENT_REGION }}
      - name: Create Amplify deployment
        id: create_deployment
        run: |
          output=$(aws amplify create-deployment --app-id ${{ secrets.AWS_DOCUMENT_APP_ID }} --branch-name $BRANCH_NAME)
          echo "job_id=$(echo $output | jq -r '.jobId')" >> $GITHUB_OUTPUT
          echo "zip_upload_url=$(echo $output | jq -r '.zipUploadUrl')" >> $GITHUB_OUTPUT
      - name: Upload Document Zip file
        run: |
          echo ${{ steps.create_deployment.outputs.job_id }}
          curl -X PUT -H "Content-Type: application/zip" --upload-file "$ZIP_FILE_NAME".zip ${{ steps.create_deployment.outputs.zip_upload_url }}
      - name: Start Amplify deployment
        run: |
          aws amplify start-deployment \
            --app-id ${{ secrets.AWS_DOCUMENT_APP_ID }} \
            --branch-name $BRANCH_NAME \
            --job-id ${{ steps.create_deployment.outputs.job_id }}