name: Check v1 release

on:
  release:
    types: [created]
jobs:
  Run_tests:
    name: Prepare for the release and trigger upload workflow
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - name: Install dependencies
      run: |
        npm ci
        npm i @actions/core
    - name: Check version
      id: check_version
      uses: ./.github/actions/check_version
    - name: Run ESLint
      run: npm run es-lint
    - name: Run unit test
      run: npm test
    - name: Trigger run upload release workflows
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.WORKFLOW_TOKEN}}
        event-type: release_dispatch_v1
    # Use this to run flow auto test
    # - name: Trigger run automation test
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{secrets.WORKFLOW_TOKEN}}
    #     repository: SDQA-VN/ui-component-auto
    #     event-type: kuc-trigger-auto-test-release
    #     client-payload: '{"repository": "${{github.repository}}", "responseType": "release_dispatch"}'