name: Check v1 release

on:
  release:
    types: [created]
jobs:
  Run_tests:
    name: Prepare for the release and trigger upload workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('./pnpm-lock.yaml') }}
        restore-keys: pnpm-
    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        pnpm add @actions/core --no-save
    - name: Check version
      id: check_version
      uses: ./.github/actions/check_version
    - name: Run ESLint
      run: pnpm run es-lint
    - name: Run unit test
      run: pnpm test
    - name: Trigger run upload release workflows
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{secrets.WORKFLOW_TOKEN}}
        event-type: release_dispatch_v1
