name: execute yamory when pushing to v0
on:
  push:
    branches: [v0_dev]

jobs:
  check_v0_dev:
    name: execute yamory on v0_dev branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run Yamory
      run: |
        bash -c "$(curl -sSf -L https://localscanner.yamory.io/script/npm)"
      env:
        CI: true
        PROJECT_GROUP_KEY: kintone-ui-component_v0_dev
        YAMORY_API_KEY: ${{ secrets.YAMORY_API_KEY }}
     - name: run Yamory_docs
      working-directory: docs
      run: |
        bash -c "$(curl -sSf -L https://localscanner.yamory.io/script/pip)"
      env:
        CI: true
        PROJECT_GROUP_KEY: kintone-ui-component_v0_dev
        YAMORY_API_KEY: ${{ secrets.YAMORY_API_KEY }}