name: Check Sibz/github-status-action

on:
  push:
    branches:
      - SSR-3197-Fix-warning-node12-deprecation-on-CI

jobs:
  publishMasterCommit:
    name: Check Sibz/github-status-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.WORKFLOW_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://staging--kintone-ui-component.netlify.app
